version: '3'
services:
  spring-server:
    build: .
#    depends_on:
#      - mysql

#  mysql:
#    image: mysql:latest
#    environment:
#      - MYSQL_ROOT_PASSWORD=123456
#      - MYSQL_DATABASE=b2c_docker
#    ports:
#      - "3307:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#      - ./b2c_docker.sql:/docker-entrypoint-initdb.d/init.sql
#
#volumes:
#  mysql_data: